# Train Basic Hairstyle Attribute Predictor

Lightweight multi-head classifier for the reviewed kept-asset basic fields: `length` and `curl`.

In [1]:
import json
from pathlib import Path
import sys
import time

import pandas as pd

def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'backend').exists() and (candidate / 'notebooks').exists():
            return candidate
    raise RuntimeError('Could not locate project root.')

def format_seconds(seconds: float) -> str:
    total_seconds = max(0, int(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f'{hours:d}:{minutes:02d}:{secs:02d}'
    return f'{minutes:02d}:{secs:02d}'

def resolve_training_device(torch_module, require_gpu: bool = True) -> str:
    if torch_module.cuda.is_available():
        return 'cuda'
    if require_gpu:
        raise RuntimeError(
            'CUDA GPU is required for this training run, but the current PyTorch build does not have CUDA available. '
            'Install a CUDA-enabled PyTorch build into .venv and restart the notebook kernel.'
        )
    return 'cpu'

PROJECT_ROOT = find_project_root(Path.cwd().resolve())
BACKEND_ROOT = PROJECT_ROOT / 'backend'
if str(BACKEND_ROOT) not in sys.path:
    sys.path.append(str(BACKEND_ROOT))

import torch
from torch.utils.data import DataLoader

from systems.static_auto_tryon.auto_app.ml.datasets import MultiAttributeDataset, read_jsonl_manifest
from systems.static_auto_tryon.auto_app.ml.hairstyle_attribute_model import build_attribute_model, multitask_cross_entropy
from systems.static_auto_tryon.auto_app.ml.metrics import attribute_accuracy, exact_match_accuracy
from systems.static_auto_tryon.auto_app.ml.transforms import ResizeImage

PROJECT_ROOT

WindowsPath('.')

In [2]:
DATASET_ROOT = PROJECT_ROOT / 'backend' / 'data' / 'datasets' / 'reviewed_hairstyle_basic'
TRAIN_MANIFEST = DATASET_ROOT / 'train.jsonl'
VAL_MANIFEST = DATASET_ROOT / 'val.jsonl'
VOCAB_PATH = DATASET_ROOT / 'label_vocab.json'
SUMMARY_PATH = DATASET_ROOT / 'summary.json'
CHECKPOINT_PATH = PROJECT_ROOT / 'backend' / 'models' / 'reviewed_hairstyle_basic' / 'basic_attribute_model.pt'

REQUIRE_GPU = True
IMAGE_SIZE = 224
BATCH_SIZE = 16
EPOCHS = 30
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 0
DEVICE = resolve_training_device(torch, require_gpu=REQUIRE_GPU)

CORE_FIELDS = ('length', 'curl')

In [3]:
train_records = read_jsonl_manifest(TRAIN_MANIFEST)
val_records = read_jsonl_manifest(VAL_MANIFEST)
label_vocab = json.loads(VOCAB_PATH.read_text(encoding='utf-8'))
summary = json.loads(SUMMARY_PATH.read_text(encoding='utf-8'))

attribute_vocab_sizes = {field: len(label_vocab[field]) for field in CORE_FIELDS}

print('Device:', DEVICE)
print('Torch version:', torch.__version__)
print('CUDA version:', torch.version.cuda)
print('Core fields:', CORE_FIELDS)
print('Train records:', len(train_records))
print('Val records:', len(val_records))
summary

Device: cuda
Torch version: 2.11.0+cu128
CUDA version: 12.8
Core fields: ('length', 'curl')
Train records: 67
Val records: 17

{'core_fields': ['length', 'curl'],
 'total_records': 84,
 'train_records': 67,
 'val_records': 17,
 'train_ratio': 0.8,
 'field_value_counts': {'length': {'long': 44, 'short': 35, 'medium': 5},
  'curl': {'straight': 45, 'wavy': 37, 'curly': 2}}}

In [4]:
transform = ResizeImage((IMAGE_SIZE, IMAGE_SIZE))

train_dataset = MultiAttributeDataset(
    train_records,
    label_vocab=label_vocab,
    transform=transform,
    fields=CORE_FIELDS,
)
val_dataset = MultiAttributeDataset(
    val_records,
    label_vocab=label_vocab,
    transform=transform,
    fields=CORE_FIELDS,
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

batch = next(iter(train_loader))
batch['image'].shape, {field: tensor.shape for field, tensor in batch['labels'].items()}

(torch.Size([16, 3, 224, 224]),
 {'length': torch.Size([16]), 'curl': torch.Size([16])})

In [5]:
model = build_attribute_model(attribute_vocab_sizes=attribute_vocab_sizes, base_channels=32, dropout=0.2).to(DEVICE)
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)

sum(parameter.numel() for parameter in model.parameters())

1174758

In [6]:
def move_targets_to_device(targets, device):
    return {field: tensor.to(device) for field, tensor in targets.items()}

def filter_outputs(outputs, fields):
    return {field: outputs[field] for field in fields}

def train_one_epoch(model, loader, optimizer, device):
    model.train()
    running_loss = 0.0
    total_batches = 0
    for batch in loader:
        images = batch['image'].to(device)
        targets = move_targets_to_device(batch['labels'], device)
        optimizer.zero_grad(set_to_none=True)
        outputs = model(images)
        outputs = filter_outputs(outputs, CORE_FIELDS)
        loss = multitask_cross_entropy(outputs, targets)
        loss.backward()
        optimizer.step()
        running_loss += float(loss.item())
        total_batches += 1
    return running_loss / max(total_batches, 1)

def evaluate(model, loader, device):
    model.eval()
    running_loss = 0.0
    total_batches = 0
    output_batches = []
    target_batches = []

    with torch.no_grad():
        for batch in loader:
            images = batch['image'].to(device)
            targets = move_targets_to_device(batch['labels'], device)
            outputs = model(images)
            outputs = filter_outputs(outputs, CORE_FIELDS)
            loss = multitask_cross_entropy(outputs, targets)
            running_loss += float(loss.item())
            total_batches += 1
            output_batches.append({field: tensor.detach().cpu() for field, tensor in outputs.items()})
            target_batches.append({field: tensor.detach().cpu() for field, tensor in targets.items()})

    merged_outputs = {
        field: torch.cat([batch[field] for batch in output_batches], dim=0)
        for field in CORE_FIELDS
    }
    merged_targets = {
        field: torch.cat([batch[field] for batch in target_batches], dim=0)
        for field in CORE_FIELDS
    }
    attr_scores = attribute_accuracy(merged_outputs, merged_targets)
    return {
        'val_loss': running_loss / max(total_batches, 1),
        'exact_match_accuracy': exact_match_accuracy(merged_outputs, merged_targets),
        **attr_scores,
    }

In [7]:
history = []
best_metric = float('-inf')
best_epoch = None
epoch_durations = []

for epoch in range(1, EPOCHS + 1):
    print(f'Running epoch {epoch}/{EPOCHS}...')
    epoch_start = time.time()
    train_loss = train_one_epoch(model, train_loader, optimizer, DEVICE)
    metrics = evaluate(model, val_loader, DEVICE)
    epoch_duration = time.time() - epoch_start
    epoch_durations.append(epoch_duration)

    row = {
        'epoch': epoch,
        'train_loss': train_loss,
        'epoch_seconds': round(epoch_duration, 2),
        **metrics,
    }
    history.append(row)

    current_metric = metrics['exact_match_accuracy']
    if current_metric > best_metric:
        best_metric = current_metric
        best_epoch = epoch

    average_epoch_seconds = sum(epoch_durations) / len(epoch_durations)
    remaining_seconds = average_epoch_seconds * (EPOCHS - epoch)

    CHECKPOINT_PATH.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            'model_state_dict': model.state_dict(),
            'history': history,
            'last_epoch': epoch,
            'core_fields': CORE_FIELDS,
            'label_vocab': label_vocab,
        },
        CHECKPOINT_PATH,
    )

    print(f"Completed epoch {epoch}/{EPOCHS}")
    print(f"Epoch time: {format_seconds(epoch_duration)}")
    print(f"Estimated remaining: {format_seconds(remaining_seconds)}")
    print(f"Best epoch so far: {best_epoch} (exact_match_accuracy={best_metric:.4f})")
    print(row)
    display(pd.DataFrame(history))

print(f'Saved checkpoint to {CHECKPOINT_PATH}')
pd.DataFrame(history)

Running epoch 1/30...
Completed epoch 1/30
Epoch time: 00:01
Estimated remaining: 00:50
Best epoch so far: 1 (exact_match_accuracy=0.0000)
{'epoch': 1, 'train_loss': 2.0940362930297853, 'epoch_seconds': 1.73, 'val_loss': 2.2906482219696045, 'exact_match_accuracy': 0.0, 'length': 0.0, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.0,0.0,0.411765

Running epoch 2/30...
Completed epoch 2/30
Epoch time: 00:00
Estimated remaining: 00:28
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 2, 'train_loss': 1.9759682178497315, 'epoch_seconds': 0.33, 'val_loss': 2.327877640724182, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765

Running epoch 3/30...
Completed epoch 3/30
Epoch time: 00:00
Estimated remaining: 00:21
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 3, 'train_loss': 1.906791877746582, 'epoch_seconds': 0.33, 'val_loss': 2.317282199859619, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765

Running epoch 4/30...
Completed epoch 4/30
Epoch time: 00:00
Estimated remaining: 00:17
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 4, 'train_loss': 1.5676028728485107, 'epoch_seconds': 0.34, 'val_loss': 2.4870764017105103, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765

Running epoch 5/30...
Completed epoch 5/30
Epoch time: 00:00
Estimated remaining: 00:15
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 5, 'train_loss': 1.508034062385559, 'epoch_seconds': 0.3, 'val_loss': 2.7992517948150635, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765

Running epoch 6/30...
Completed epoch 6/30
Epoch time: 00:00
Estimated remaining: 00:13
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 6, 'train_loss': 1.4326189279556274, 'epoch_seconds': 0.28, 'val_loss': 2.8155009746551514, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765

Running epoch 7/30...
Completed epoch 7/30
Epoch time: 00:00
Estimated remaining: 00:11
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 7, 'train_loss': 1.3229889869689941, 'epoch_seconds': 0.32, 'val_loss': 2.457396984100342, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765

Running epoch 8/30...
Completed epoch 8/30
Epoch time: 00:00
Estimated remaining: 00:10
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 8, 'train_loss': 1.064181923866272, 'epoch_seconds': 0.3, 'val_loss': 2.077426791191101, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.3529411852359772}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941

Running epoch 9/30...
Completed epoch 9/30
Epoch time: 00:00
Estimated remaining: 00:09
Best epoch so far: 2 (exact_match_accuracy=0.2941)
{'epoch': 9, 'train_loss': 1.129020881652832, 'epoch_seconds': 0.29, 'val_loss': 1.6149186193943024, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.47058823704719543, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765

Running epoch 10/30...
Completed epoch 10/30
Epoch time: 00:00
Estimated remaining: 00:09
Best epoch so far: 10 (exact_match_accuracy=0.4118)
{'epoch': 10, 'train_loss': 1.0265137076377868, 'epoch_seconds': 0.29, 'val_loss': 1.7272765338420868, 'exact_match_accuracy': 0.4117647111415863, 'length': 0.529411792755127, 'curl': 0.47058823704719543}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588

Running epoch 11/30...
Completed epoch 11/30
Epoch time: 00:00
Estimated remaining: 00:08
Best epoch so far: 10 (exact_match_accuracy=0.4118)
{'epoch': 11, 'train_loss': 0.9469285607337952, 'epoch_seconds': 0.31, 'val_loss': 1.529670238494873, 'exact_match_accuracy': 0.4117647111415863, 'length': 0.7058823704719543, 'curl': 0.529411792755127}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412

Running epoch 12/30...
Completed epoch 12/30
Epoch time: 00:00
Estimated remaining: 00:07
Best epoch so far: 10 (exact_match_accuracy=0.4118)
{'epoch': 12, 'train_loss': 0.8768985986709594, 'epoch_seconds': 0.29, 'val_loss': 1.4496977925300598, 'exact_match_accuracy': 0.3529411852359772, 'length': 0.6470588445663452, 'curl': 0.3529411852359772}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941

Running epoch 13/30...
Completed epoch 13/30
Epoch time: 00:00
Estimated remaining: 00:07
Best epoch so far: 13 (exact_match_accuracy=0.4706)
{'epoch': 13, 'train_loss': 0.8680673480033875, 'epoch_seconds': 0.32, 'val_loss': 1.3513393998146057, 'exact_match_accuracy': 0.47058823704719543, 'length': 0.7058823704719543, 'curl': 0.5882353186607361}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235

Running epoch 14/30...
Completed epoch 14/30
Epoch time: 00:00
Estimated remaining: 00:06
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 14, 'train_loss': 0.9991751194000245, 'epoch_seconds': 0.32, 'val_loss': 1.4571066498756409, 'exact_match_accuracy': 0.529411792755127, 'length': 0.8235294222831726, 'curl': 0.5882353186607361}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235

Running epoch 15/30...
Completed epoch 15/30
Epoch time: 00:00
Estimated remaining: 00:06
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 15, 'train_loss': 0.9447006940841675, 'epoch_seconds': 0.31, 'val_loss': 1.8406389355659485, 'exact_match_accuracy': 0.47058823704719543, 'length': 0.7647058963775635, 'curl': 0.529411792755127}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412

Running epoch 16/30...
Completed epoch 16/30
Epoch time: 00:00
Estimated remaining: 00:05
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 16, 'train_loss': 0.9550292074680329, 'epoch_seconds': 0.31, 'val_loss': 1.9864056706428528, 'exact_match_accuracy': 0.3529411852359772, 'length': 0.5882353186607361, 'curl': 0.4117647111415863}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765

Running epoch 17/30...
Completed epoch 17/30
Epoch time: 00:00
Estimated remaining: 00:05
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 17, 'train_loss': 1.1105939865112304, 'epoch_seconds': 0.31, 'val_loss': 1.9577190279960632, 'exact_match_accuracy': 0.3529411852359772, 'length': 0.5882353186607361, 'curl': 0.47058823704719543}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588

Running epoch 18/30...
Completed epoch 18/30
Epoch time: 00:00
Estimated remaining: 00:04
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 18, 'train_loss': 1.0023112535476684, 'epoch_seconds': 0.31, 'val_loss': 1.6057389378547668, 'exact_match_accuracy': 0.47058823704719543, 'length': 0.7058823704719543, 'curl': 0.529411792755127}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412

Running epoch 19/30...
Completed epoch 19/30
Epoch time: 00:00
Estimated remaining: 00:04
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 19, 'train_loss': 0.9513739585876465, 'epoch_seconds': 0.33, 'val_loss': 2.3081055879592896, 'exact_match_accuracy': 0.529411792755127, 'length': 0.6470588445663452, 'curl': 0.5882353186607361}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235

Running epoch 20/30...
Completed epoch 20/30
Epoch time: 00:00
Estimated remaining: 00:03
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 20, 'train_loss': 0.659358024597168, 'epoch_seconds': 0.32, 'val_loss': 1.8929867148399353, 'exact_match_accuracy': 0.29411765933036804, 'length': 0.7058823704719543, 'curl': 0.47058823704719543}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588

Running epoch 21/30...
Completed epoch 21/30
Epoch time: 00:00
Estimated remaining: 00:03
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 21, 'train_loss': 0.690604853630066, 'epoch_seconds': 0.31, 'val_loss': 1.2342916429042816, 'exact_match_accuracy': 0.47058823704719543, 'length': 0.8823529481887817, 'curl': 0.529411792755127}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412

Running epoch 22/30...
Completed epoch 22/30
Epoch time: 00:00
Estimated remaining: 00:03
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 22, 'train_loss': 0.6711386740207672, 'epoch_seconds': 0.46, 'val_loss': 1.043799839913845, 'exact_match_accuracy': 0.3529411852359772, 'length': 0.6470588445663452, 'curl': 0.5882353186607361}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235

Running epoch 23/30...
Completed epoch 23/30
Epoch time: 00:00
Estimated remaining: 00:02
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 23, 'train_loss': 0.5275459527969361, 'epoch_seconds': 0.38, 'val_loss': 2.037866711616516, 'exact_match_accuracy': 0.3529411852359772, 'length': 0.5882353186607361, 'curl': 0.5882353186607361}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235

Running epoch 24/30...
Completed epoch 24/30
Epoch time: 00:00
Estimated remaining: 00:02
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 24, 'train_loss': 0.6492704451084137, 'epoch_seconds': 0.33, 'val_loss': 1.6355813145637512, 'exact_match_accuracy': 0.4117647111415863, 'length': 0.6470588445663452, 'curl': 0.529411792755127}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412

Running epoch 25/30...
Completed epoch 25/30
Epoch time: 00:00
Estimated remaining: 00:01
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 25, 'train_loss': 0.5904239296913147, 'epoch_seconds': 0.39, 'val_loss': 1.0987295806407928, 'exact_match_accuracy': 0.47058823704719543, 'length': 0.7058823704719543, 'curl': 0.6470588445663452}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412
24,25,0.590424,0.39,1.098730,0.470588,0.705882,0.647059

Running epoch 26/30...
Completed epoch 26/30
Epoch time: 00:00
Estimated remaining: 00:01
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 26, 'train_loss': 0.3752042889595032, 'epoch_seconds': 0.34, 'val_loss': 1.1402076296508312, 'exact_match_accuracy': 0.529411792755127, 'length': 0.6470588445663452, 'curl': 0.6470588445663452}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412
24,25,0.590424,0.39,1.098730,0.470588,0.705882,0.647059
25,26,0.375204,0.34,1.140208,0.529412,0.647059,0.647059

Running epoch 27/30...
Completed epoch 27/30
Epoch time: 00:00
Estimated remaining: 00:01
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 27, 'train_loss': 0.4824866890907288, 'epoch_seconds': 0.31, 'val_loss': 1.1737647633999586, 'exact_match_accuracy': 0.4117647111415863, 'length': 0.6470588445663452, 'curl': 0.5882353186607361}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412
24,25,0.590424,0.39,1.098730,0.470588,0.705882,0.647059
25,26,0.375204,0.34,1.140208,0.529412,0.647059,0.647059
26,27,0.482487,0.31,1.173765,0.411765,0.647059,0.588235

Running epoch 28/30...
Completed epoch 28/30
Epoch time: 00:00
Estimated remaining: 00:00
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 28, 'train_loss': 0.3869543492794037, 'epoch_seconds': 0.31, 'val_loss': 1.0447134003043175, 'exact_match_accuracy': 0.529411792755127, 'length': 0.6470588445663452, 'curl': 0.6470588445663452}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412
24,25,0.590424,0.39,1.098730,0.470588,0.705882,0.647059
25,26,0.375204,0.34,1.140208,0.529412,0.647059,0.647059
26,27,0.482487,0.31,1.173765,0.411765,0.647059,0.588235
27,28,0.386954,0.31,1.044713,0.529412,0.647059,0.647059

Running epoch 29/30...
Completed epoch 29/30
Epoch time: 00:00
Estimated remaining: 00:00
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 29, 'train_loss': 0.5553351104259491, 'epoch_seconds': 0.32, 'val_loss': 1.310118317604065, 'exact_match_accuracy': 0.47058823704719543, 'length': 0.5882353186607361, 'curl': 0.7058823704719543}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412
24,25,0.590424,0.39,1.098730,0.470588,0.705882,0.647059
25,26,0.375204,0.34,1.140208,0.529412,0.647059,0.647059
26,27,0.482487,0.31,1.173765,0.411765,0.647059,0.588235
27,28,0.386954,0.31,1.044713,0.529412,0.647059,0.647059
28,29,0.555335,0.32,1.310118,0.470588,0.588235,0.705882

Running epoch 30/30...
Completed epoch 30/30
Epoch time: 00:00
Estimated remaining: 00:00
Best epoch so far: 14 (exact_match_accuracy=0.5294)
{'epoch': 30, 'train_loss': 0.4604868531227112, 'epoch_seconds': 0.32, 'val_loss': 0.9454998597502708, 'exact_match_accuracy': 0.47058823704719543, 'length': 0.7058823704719543, 'curl': 0.5882353186607361}

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412
24,25,0.590424,0.39,1.098730,0.470588,0.705882,0.647059
25,26,0.375204,0.34,1.140208,0.529412,0.647059,0.647059
26,27,0.482487,0.31,1.173765,0.411765,0.647059,0.588235
27,28,0.386954,0.31,1.044713,0.529412,0.647059,0.647059
28,29,0.555335,0.32,1.310118,0.470588,0.588235,0.705882
29,30,0.460487,0.32,0.945500,0.470588,0.705882,0.588235

Saved checkpoint to backend/models\reviewed_hairstyle_basic\basic_attribute_model.pt

,epoch,train_loss,epoch_seconds,val_loss,exact_match_accuracy,length,curl
0,1,2.094036,1.73,2.290648,0.000000,0.000000,0.411765
1,2,1.975968,0.33,2.327878,0.294118,0.470588,0.411765
2,3,1.906792,0.33,2.317282,0.294118,0.470588,0.411765
3,4,1.567603,0.34,2.487076,0.294118,0.470588,0.411765
4,5,1.508034,0.30,2.799252,0.294118,0.470588,0.411765
5,6,1.432619,0.28,2.815501,0.294118,0.470588,0.411765
6,7,1.322989,0.32,2.457397,0.294118,0.470588,0.411765
7,8,1.064182,0.30,2.077427,0.294118,0.470588,0.352941
8,9,1.129021,0.29,1.614919,0.294118,0.470588,0.411765
9,10,1.026514,0.29,1.727277,0.411765,0.529412,0.470588
10,11,0.946929,0.31,1.529670,0.411765,0.705882,0.529412
11,12,0.876899,0.29,1.449698,0.352941,0.647059,0.352941
12,13,0.868067,0.32,1.351339,0.470588,0.705882,0.588235
13,14,0.999175,0.32,1.457107,0.529412,0.823529,0.588235
14,15,0.944701,0.31,1.840639,0.470588,0.764706,0.529412
15,16,0.955029,0.31,1.986406,0.352941,0.588235,0.411765
16,17,1.110594,0.31,1.957719,0.352941,0.588235,0.470588
17,18,1.002311,0.31,1.605739,0.470588,0.705882,0.529412
18,19,0.951374,0.33,2.308106,0.529412,0.647059,0.588235
19,20,0.659358,0.32,1.892987,0.294118,0.705882,0.470588
20,21,0.690605,0.31,1.234292,0.470588,0.882353,0.529412
21,22,0.671139,0.46,1.043800,0.352941,0.647059,0.588235
22,23,0.527546,0.38,2.037867,0.352941,0.588235,0.588235
23,24,0.649270,0.33,1.635581,0.411765,0.647059,0.529412
24,25,0.590424,0.39,1.098730,0.470588,0.705882,0.647059
25,26,0.375204,0.34,1.140208,0.529412,0.647059,0.647059
26,27,0.482487,0.31,1.173765,0.411765,0.647059,0.588235
27,28,0.386954,0.31,1.044713,0.529412,0.647059,0.647059
28,29,0.555335,0.32,1.310118,0.470588,0.588235,0.705882
29,30,0.460487,0.32,0.945500,0.470588,0.705882,0.588235